### ISSUE TITLE
Docs no longer building

### ISSUE THREAD

**Issue by ianmkenney** [MDAnalysis/cookiecutter-mdakit#56]
The scheduled CI and PR CI are failing due to docs not building. This happened in the hole2-mdakit due to Sphinx 7. The quick fix is to pin the version of sphinx to a working one.

We should probably address this properly though since all MDAKits generated from the cookiecutter will probably fail in the same way.

**Comment by lilyminium** [comment]
Ok, I'm a bit mystified by this. The error is:

```
preparing documents... done
writing output... [ 12%] cookiecutter/hooks
Theme error:
An error happened in rendering the page cookiecutter/hooks.
Reason: UndefinedError("'style' is undefined")
```
There's nothing special about hooks that I can tell, just that it's the first to be rendered. This is clearly because of https://github.com/sphinx-doc/sphinx/pull/11381 , but I can't see that we use the `style` or `styles` keyword anywhere, or in sphinx_rtd_theme (just from a ctrl+f through its repo). That being said, changing from sphinx_rtd_theme to anything else does allow docs to build, so it could be something there. We should definitely revisit this but I vote for pinning sphinx lower for now.

**Comment by ianmkenney** [comment]
Agreed, I think pinning is a good option until we know more.
